class State{
    constructor(){
        this.title1 = createElement('h1');
        this.title2 = createElement('h1');
        this.button1 = createButton('ANDHRA PRADESH');
        this.button2 = createButton('ASSAM');
        this.button3 = createButton('ARUNACHAL PRADESH');
        this.button4 = createButton('BIHAR');
        this.button5 = createButton('CHHATTISGARH');
        this.button6 = createButton('GOA');
        this.button7 = createButton('GUJARAT');
        this.button8 = createButton('HARYANA');
        this.button9 = createButton('HIMACHAL PRADESH');
        this.button10 = createButton('JHARKHAND');
        this.button11 = createButton('KARNATAKA');
        this.button12 = createButton('KERALA');
        this.button13 = createButton('MADHYA PRADESH');
        this.button14 = createButton('MAHARASHTRA');
        this.button15 = createButton('MANIPUR');
        this.button16 = createButton('MEGHALAYA');
        this.button17 = createButton('MIZORAM');
        this.button18 = createButton('NAGALAND');
        this.button19 = createButton('ODISHA');
        this.button20 = createButton('PUNJAB');
        this.button21 = createButton('RAJASTHAN');
        this.button22 = createButton('SIKKIM');
        this.button23 = createButton('TAMIL NADU');
        this.button24 = createButton('TELENGANA');
        this.button25 = createButton('TRIPURA');
        this.button26 = createButton('UTTAR PRADESH');
        this.button27 = createButton('UTTARAKHAND');
        this.button28 = createButton('WEST BENGAL');
    }

    display(){
        this.title1.position(650,30);
        this.title1.html("STATES OF");
        this.title1.style('color','purple');
        this.title2.position(800,60);
        this.title2.html("INDIA");
        this.title2.style('color','purple');
        this.button1.position(460,200);
        this.button2.position(610,200);
        this.button3.position(690,200);
        this.button4.position(870,200);
        this.button5.position(940,200);
        this.button6.position(1070,200);
        this.button7.position(460,300);
        this.button8.position(550,300);
        this.button9.position(640,300);
        this.button10.position(810,300);
        this.button11.position(930,300);
        this.button12.position(1040,300);
        this.button13.position(460,400);
        this.button14.position(610,400);
        this.button15.position(740,400);
        this.button16.position(830,400);
        this.button17.position(940,400);
        this.button18.position(1030,400);
        this.button19.position(460,500);
        this.button20.position(540,500);
        this.button21.position(620,500);
        this.button22.position(730,500);
        this.button23.position(810,500);
        this.button24.position(930,500);
        this.button25.position(1040,500);
        this.button26.position(600,600);
        this.button27.position(740,600);
        this.button28.position(870,600);

        this.button1.mousePressed(()=>{
            this.title1.hide();
            this.title2.hide();
            this.button1.hide();
            this.button2.hide();
            this.button3.hide();
            this.button4.hide();
            this.button5.hide();
            this.button6.hide();
            this.button7.hide();
            this.button8.hide();
            this.button9.hide();
            this.button10.hide();
            this.button11.hide();
            this.button12.hide();
            this.button13.hide();
            this.button14.hide();
            this.button15.hide();
            this.button16.hide();
            this.button17.hide();
            this.button18.hide();
            this.button19.hide();
            this.button20.hide();
            this.button21.hide();
            this.button22.hide();
            this.button23.hide();
            this.button24.hide();
            this.button25.hide();
            this.button26.hide();
            this.button27.hide();
            this.button28.hide();
            s1 = new S1();
            s1.display();
            back.mousePressed(()=>{
                s1.opt1.hide();
                s1.opt2.hide();
                s1.opt3.hide();
                s1.opt4.hide();
                s1.opt5.hide();
                s1.opt6.hide();
                s1.title.hide();
                back.hide();

            this.title1.show();
            this.title2.show();
            this.button1.show();
            this.button2.show();
            this.button3.show();
            this.button4.show();
            this.button5.show();
            this.button6.show();
            this.button7.show();
            this.button8.show();
            this.button9.show();
            this.button10.show();
            this.button11.show();
            this.button12.show();
            this.button13.show();
            this.button14.show();
            this.button15.show();
            this.button16.show();
            this.button17.show();
            this.button18.show();
            this.button19.show();
            this.button20.show();
            this.button21.show();
            this.button22.show();
            this.button23.show();
            this.button24.show();
            this.button25.show();
            this.button26.show();
            this.button27.show();
            this.button28.show();
            gs = 0;
            })
        })

        
        this.button2.mousePressed(()=>{
            this.title1.hide();
            this.title2.hide();
            this.button1.hide();
            this.button2.hide();
            this.button3.hide();
            this.button4.hide();
            this.button5.hide();
            this.button6.hide();
            this.button7.hide();
            this.button8.hide();
            this.button9.hide();
            this.button10.hide();
            this.button11.hide();
            this.button12.hide();
            this.button13.hide();
            this.button14.hide();
            this.button15.hide();
            this.button16.hide();
            this.button17.hide();
            this.button18.hide();
            this.button19.hide();
            this.button20.hide();
            this.button21.hide();
            this.button22.hide();
            this.button23.hide();
            this.button24.hide();
            this.button25.hide();
            this.button26.hide();
            this.button27.hide();
            this.button28.hide();
            s2 = new S2();
            s2.display();
            back.mousePressed(()=>{
                s2.opt1.hide();
                s2.opt2.hide();
                s2.opt3.hide();
                s2.opt4.hide();
                s2.opt5.hide();
                s2.opt6.hide();
                s2.title.hide();
                back.hide();

            this.title1.show();
            this.title2.show();
            this.button1.show();
            this.button2.show();
            this.button3.show();
            this.button4.show();
            this.button5.show();
            this.button6.show();
            this.button7.show();
            this.button8.show();
            this.button9.show();
            this.button10.show();
            this.button11.show();
            this.button12.show();
            this.button13.show();
            this.button14.show();
            this.button15.show();
            this.button16.show();
            this.button17.show();
            this.button18.show();
            this.button19.show();
            this.button20.show();
            this.button21.show();
            this.button22.show();
            this.button23.show();
            this.button24.show();
            this.button25.show();
            this.button26.show();
            this.button27.show();
            this.button28.show();
            gs = 0;
            })
        })
    }
}